set number
set relativenumber
syntax on
set smartindent
set tabstop=4
set shiftwidth=4
set expandtab
set softtabstop=4
colorscheme murphy
set laststatus=2
set hlsearch
set list listchars=trail:-
set ttimeout
set ttimeoutlen=50
set cursorline
packadd! nohlsearch
" in contontest, use this one-liner:
" syn on | se nu rnu si ts=4 sw=4 et sts ls hls list lcs=trail:- ttimeout ttm=50 cul | pa! nohlsearch
" colo murphy
set nowrap
map <Leader>y "+y
map <Leader>p "+p
